### ISSUE TITLE
TopNavLink should include `to` support

### ISSUE THREAD

**Issue by ajturner** [Esri/calcite-react#235]
`TopNavLink` and `SideNavLink` should support `to` parameter for dynamic routing.

**Comment by jpeterson** [comment]
Hey @ajturner! I think this may just be a hole in our docs. 

While we don't think Calcite React should be in the router game, it is very easy to integrate with router libraries by using the `as` prop. It looks like we haven't done a great job documenting `as`... but it allows you to change the rendered component - and since we pass all your props to the rendered component, you can do things like this:

```jsx
<TopNavLink as={NavLink} to="/plans">Plans</TopNavLink>
```

Here's a simple example:
https://codesandbox.io/s/wwx035kyx8

**Comment by jpeterson** [comment]
Closing this one for now (will work on #236). @ajturner please let us know if this doesn't meet your need.
