### ISSUE TITLE
Implement defaultProps theme for styled components

### ISSUE THREAD

**Issue by codylawson** [Esri/calcite-react#286]
## Expected Behavior
Styled components should have a theme defined as a `defaultProp` so that users don't have to use a `CalciteThemeProvider` if they're not changing any of the theme values. This should also resolve some issues with unit testing our components.

## Current Behavior
Currently require a theme provider for components to render.

## Context + Screenshots
https://www.styled-components.com/docs/advanced#theming

```
Button.defaultProps = {
  theme: {
    palette: ...,
    ...
  }
}
```

**Comment by jgibson02** [comment]
@codylawson what are your thoughts on implementing this by importing the theme object exported by `CalciteTheme.js` and assigning that in `defaultProps` for each styled-component.
e.g. (`Accordion-styled.js`)
```
import theme from '../CalciteThemeProvider/CalciteTheme';

const StyledAccordion = styled(StyledSideNav)`
  border-radius: ${props => props.theme.borderRadius};
`;
StyledAccordion.defaultProps = { theme };
```

**Comment by codylawson** [comment]
@jgibson02 that's what I was thinking. Im not sure if there's any performance concerns with that approach though. And it seems mind numbing...

**Comment by jgibson02** [comment]
I was thinking about this some more and this still seems like the best approach unless we were exporting all of our styled-components in a monolithic `index.js` where we could initialize the theme object once and set the `defaultProps` for each export. I think due to the nature of ES6 we'll just have to live with creating an instance of `theme` for each module.

**Comment by jpeterson** [comment]
@jgibson02 this can be closed, yeah?
