### ISSUE TITLE
Buttons in ButtonGroup in an Adornment are mis-aligned

### ISSUE THREAD

**Issue by gavinr** [Esri/calcite-react#360]
## Expected Behavior
ButtonGroup works in Adornment

## Current Behavior
The buttons are not aligned when used like that ^

## Steps to Reproduce (for bugs)
Live example: https://codesandbox.io/s/calcite-react-buttongroup-in-rightadornment-possible-issue-3rcjm

## Context + Screenshots
Buttons not aligned:
![image](https://user-images.githubusercontent.com/209355/77792426-42510a00-7060-11ea-863d-8216ffd6c3d0.png)

**Comment by codylawson** [comment]
Thanks @gavinr. The `adornment` implementation has some special styling for certain components, `Button` and `Select`, otherwise it assumes you want a nice background color and  padding to go with your adornment content 😉. You can opt out of this by using the `rightAdornmentNoWrap` or `leftAdornmentNoWrap` prop.

Obviously we should handle `ButtonGroup` in the same way as `Button` and `Select` so I'll start working on a PR to resolve this.
